apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: file-rouge-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.5.1
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.retention.hours: 168  # 7 jours
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: standard
    authorization:
      type: simple
    metrics: {}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      class: standard
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: file-rouge-user
  namespace: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Write
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: Read
  # Si tu veux stocker le secret dans Vault, tu peux référencer Vault ici via initContainer ou external secret
